--- # INTERACTIVE PLAYBOOK 
- hosts: ubuntu
  become: yes
  gather_facts: no
  vars:
    playbook_version: 0.1
  vars_prompt:
    - name: pkgtoinstall
      prompt: Package To Install? 
      default: telnet
      private: no
  tasks:
    - name: Install the given Package
      yum: pkg={{ pkgtoinstall }} state=present