--- # RUNONCE PLAYBOOK EXAMPLE
- hosts: all
  user: ec2-user
  gather_facts: no
  connection: ssh
  tasks:
    - name: Run the uptime command on all hosts and log it 
      raw: /usr/bin/uptime >> ~/uptime.log
    - name: List the /var directory and log it
      raw: ls -al /var >> ~/dir.list
      run_once: yes