--- # UNTIL EXAMPLE
- hosts: rhel
  become: yes
  gather_facts: no
  tasks:
    - name: Installing apache web server
      yum: pkg=httpd state=present
    - name: Verify Service Status
      shell: systemctl status httpd
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 10
      delay: 5 
    - debug: var=result
