- name: Restart HTTPD on RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
- name: Restart Apache on Debian
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"